### ISSUE TITLE
How can I force my (hex) object property names to be stored as strings rather than be converted to decimals?

### ISSUE THREAD

**Issue by viziionary** [cocobelgica/AutoHotkey-JSON#10]
I'm storing a dictionary-like structure where I need to check if a color exists in a large list of colors. Best way to do that is like `if (colors["0x680000"])` so I generate an object like that but I need to save the object, so I export to JSON. Problem is, during the export, the hex values are treated as numbers (even though they're property names, and could probably safely be treated as strings) so they're converted to decimal. I need to figure out a way to store the object keys as strings rather than numbers so they stay in the format `"0x680000" : {}` in the JSON file.

**Comment by cocobelgica** [comment]
Hi, I am on mobile right now, I'll look into this as soon as I have access to my laptop. Btw, when you export to JSON, is the decimal number quoted?
