### ISSUE TITLE
Numeric values get saved not as strings, but as null/true/false

### ISSUE THREAD

**Issue by Drugoy** [cocobelgica/AutoHotkey-JSON#4]
STR:
1. <a href="https://gist.github.com/Drugoy/7905a4c8fc4167098bf2#file-netstanddescription">Run this script</a>
2. Fill "name" = 2 and "default route" = 3.
3. Hit 'Save' button and save the data into an external file in JSON.
4. Open that file (or drag'n'drop it onto the script).

Actual result:
2 and 3 got transformed to 'null'.

Expected result:
They should get saved as strings.

1 and 0 get transformed to 'true' and 'false' respectively.

**Comment by Drugoy** [comment]
1. I might have mistakenly copied the wrong code, because I've tried now the script from the url I gave you and it seemed to not work: the script should save json into a file, but in fact it just created a blank file. I've now updated the code on that url and it now works and you should be able to reproduce the issue using the STR provided in the initial post.
2. I was not talking about the Edit controls being empty or not, I was referring to the work of your lib: you confirm that if 'name' and 'defroute' are blank - then their values get converted into JSON format as 'null'.
But I, as a user, expect them to be converted as strings (obviously empty ones).
The same goes for numeric values: imagine a different script where user would store some numbers into 'edit' controls and then would make an attempt to convert them to JSON using your lib: all the positive numbers would get converted to 'true' and the numeric values would just get lost!

It looks like a bug to me, although to you it probably looks like a 'the way it was designed'.
If so - I don't insist on committing changes to your lib if you don't want that. But then, please, at least tell me how to do what I want and I will commit these changes to my local copy of your lib.
Thanks in advance.

**Comment by cocobelgica** [comment]
I guess you have a point. Since AHK does not support `null` natively and `true`/`false` are simply `1` and `0` _(respectively)_, I opted to output `""`, `1` and `0` as they are. _See commit_ https://github.com/cocobelgica/AutoHotkey-JSON/commit/a7be08ffdf036e438db9af34f8ff838a95884f14

**Comment by Drugoy** [comment]
Thank you!
