### ISSUE TITLE
Please add some more meta info

### ISSUE THREAD

**Issue by Drugoy** [cocobelgica/AutoHotkey-JSON#5]
Hi, could you please add the url to this repo right into the script's body and some email contact of yours (as the author) as well as the version and timestamp of latest change.
This would be handy: I use helluva ton of scripts and libs and I don't always remember where I took what from. And it's a PitA to check for scripts/libs updates, when a lib lacks that metainfo.

**Comment by cocobelgica** [comment]
Done, see https://github.com/cocobelgica/AutoHotkey-JSON/commit/f6b7ccd8735aa0b3d360d4fe297b114bd1f20572. Also, you might want to update your copy to the latest version, I have made some major changes. No change in API, just some improvements on internal stuff. See: https://github.com/cocobelgica/AutoHotkey-JSON/commit/834f5f6015529b2bb38bf8fea752bafe108ead05

**Comment by Drugoy** [comment]
Thanks.
Also I did update, yet I forgot to tell you, that in case something gets broken (incorrect input) - your lib throws errors about non-existent function exception()

**Comment by cocobelgica** [comment]
What  version of AutoHotkey are you using? [Exception](http://ahkscript.org/docs/commands/Throw.htm#Exception) was implemented way way back, [v1.1.04.00](http://ahkscript.org/docs/AHKL_ChangeLog.htm#v1.1.04.00) to be specific.

**Comment by Drugoy** [comment]
1.1.19.0.3

Well, I'll wait until the next exception error.
